#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''

import os

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class LinkADSL_u768k(CoreService):
    ''' This is a sample user-defined service.
    '''
    # a unique name is required, without spaces
    _name = "L_u768k"
    # you can create your own group here
    _group = "Links"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('conflinkadsl.sh', )
    # this controls the starting order vs other enabled services
    _startindex = 10
    # list of startup commands, also may be generated during startup
    _startup = ('sh conflinkadsl.sh',)
    # list of shutdown commands
    _shutdown = ()

    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Configures Queue Discipline on the device interface desired link.
            Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
        cfg = "#!/bin/sh\n"
        cfg += "# auto-generated by LinkADSL (linkasdl_u768k.py)\n"

        for ifc in node.netifs():
            cfg += 'echo "Node %s has interface %s active"\n' % (node.name, ifc.name)
            # here we do something interesting
            cfg += "\n".join(map(cls.subnetentry, ifc.addrlist))
            break
        cfg += "# LINK TBF parameters to modify in following variables:\n"
        cfg += "RATE='768kbit'\n"
        cfg += "BURST='8000b'\n"
        cfg += "LIMIT='14000b'\n"
        cfg += "# Now apply the Qdiscipline to the interface. CONFIRM THE INTERFACE. \n"
        cfg += "tc qdisc replace dev %s root handle 1: tbf rate $RATE burst $BURST limit $LIMIT \n" % (ifc.name)
        return cfg

    @staticmethod
    def subnetentry(x):
        ''' Generate a subnet declaration block given an IPv4 prefix string
            for inclusion in the config file.
        '''
        if x.find(":") >= 0:
            # this is an IPv6 address
            return ""
        else:
            net = IPv4Prefix(x)
            return 'echo "  network %s"' % (net)

# this line is required to add the above class to the list of available services
addservice(LinkADSL_u768k)
